# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vpietropaolo/dev/curc/FAST_LIO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vpietropaolo/dev/curc/FAST_LIO

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vpietropaolo/dev/curc/FAST_LIO/CMakeFiles /Users/vpietropaolo/dev/curc/FAST_LIO//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vpietropaolo/dev/curc/FAST_LIO/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fastlio_mapping

# Build rule for target.
fastlio_mapping: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fastlio_mapping
.PHONY : fastlio_mapping

# fast build rule for target.
fastlio_mapping/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/build
.PHONY : fastlio_mapping/fast

#=============================================================================
# Target rules for targets named fastlio_mapping_shared

# Build rule for target.
fastlio_mapping_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fastlio_mapping_shared
.PHONY : fastlio_mapping_shared

# fast build rule for target.
fastlio_mapping_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/build
.PHONY : fastlio_mapping_shared/fast

include/ikd-Tree/ikd_Tree.o: include/ikd-Tree/ikd_Tree.cpp.o
.PHONY : include/ikd-Tree/ikd_Tree.o

# target to build an object file
include/ikd-Tree/ikd_Tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/include/ikd-Tree/ikd_Tree.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/include/ikd-Tree/ikd_Tree.cpp.o
.PHONY : include/ikd-Tree/ikd_Tree.cpp.o

include/ikd-Tree/ikd_Tree.i: include/ikd-Tree/ikd_Tree.cpp.i
.PHONY : include/ikd-Tree/ikd_Tree.i

# target to preprocess a source file
include/ikd-Tree/ikd_Tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/include/ikd-Tree/ikd_Tree.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/include/ikd-Tree/ikd_Tree.cpp.i
.PHONY : include/ikd-Tree/ikd_Tree.cpp.i

include/ikd-Tree/ikd_Tree.s: include/ikd-Tree/ikd_Tree.cpp.s
.PHONY : include/ikd-Tree/ikd_Tree.s

# target to generate assembly for a file
include/ikd-Tree/ikd_Tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/include/ikd-Tree/ikd_Tree.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/include/ikd-Tree/ikd_Tree.cpp.s
.PHONY : include/ikd-Tree/ikd_Tree.cpp.s

src/conversions.o: src/conversions.cpp.o
.PHONY : src/conversions.o

# target to build an object file
src/conversions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/src/conversions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/src/conversions.cpp.o
.PHONY : src/conversions.cpp.o

src/conversions.i: src/conversions.cpp.i
.PHONY : src/conversions.i

# target to preprocess a source file
src/conversions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/src/conversions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/src/conversions.cpp.i
.PHONY : src/conversions.cpp.i

src/conversions.s: src/conversions.cpp.s
.PHONY : src/conversions.s

# target to generate assembly for a file
src/conversions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/src/conversions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/src/conversions.cpp.s
.PHONY : src/conversions.cpp.s

src/laserMapping.o: src/laserMapping.cpp.o
.PHONY : src/laserMapping.o

# target to build an object file
src/laserMapping.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/src/laserMapping.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/src/laserMapping.cpp.o
.PHONY : src/laserMapping.cpp.o

src/laserMapping.i: src/laserMapping.cpp.i
.PHONY : src/laserMapping.i

# target to preprocess a source file
src/laserMapping.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/src/laserMapping.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/src/laserMapping.cpp.i
.PHONY : src/laserMapping.cpp.i

src/laserMapping.s: src/laserMapping.cpp.s
.PHONY : src/laserMapping.s

# target to generate assembly for a file
src/laserMapping.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/src/laserMapping.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/src/laserMapping.cpp.s
.PHONY : src/laserMapping.cpp.s

src/preprocess.o: src/preprocess.cpp.o
.PHONY : src/preprocess.o

# target to build an object file
src/preprocess.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/src/preprocess.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/src/preprocess.cpp.o
.PHONY : src/preprocess.cpp.o

src/preprocess.i: src/preprocess.cpp.i
.PHONY : src/preprocess.i

# target to preprocess a source file
src/preprocess.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/src/preprocess.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/src/preprocess.cpp.i
.PHONY : src/preprocess.cpp.i

src/preprocess.s: src/preprocess.cpp.s
.PHONY : src/preprocess.s

# target to generate assembly for a file
src/preprocess.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping.dir/build.make CMakeFiles/fastlio_mapping.dir/src/preprocess.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fastlio_mapping_shared.dir/build.make CMakeFiles/fastlio_mapping_shared.dir/src/preprocess.cpp.s
.PHONY : src/preprocess.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fastlio_mapping"
	@echo "... fastlio_mapping_shared"
	@echo "... include/ikd-Tree/ikd_Tree.o"
	@echo "... include/ikd-Tree/ikd_Tree.i"
	@echo "... include/ikd-Tree/ikd_Tree.s"
	@echo "... src/conversions.o"
	@echo "... src/conversions.i"
	@echo "... src/conversions.s"
	@echo "... src/laserMapping.o"
	@echo "... src/laserMapping.i"
	@echo "... src/laserMapping.s"
	@echo "... src/preprocess.o"
	@echo "... src/preprocess.i"
	@echo "... src/preprocess.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

